### ISSUE TITLE
ES6 modules and Babel for backwards compatibility

### ISSUE THREAD

**Issue by dandv** [jeffijoe/npm-module-boilerplate#3]
Similar to [this boilerplate](https://github.com/sindresorhus/node-module-boilerplate/issues/13#issuecomment-306973658).

**Comment by jeffijoe** [comment]
Could just as well be TypeScript. I use both, so not sure which one it would be.

**Comment by jeffijoe** [comment]
Closing because _if_ I do add TS/Babel, I would want it to be a separate boilerplate. This one is for "pure" Node modules written in raw JS.
